[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM6
extra_scripts = pre:embedded_compiler/platformio_prebuild.py
build_src_filter =
  +<*>
  -<web_page.cpp>
